### ISSUE TITLE
[FE] 회원 관련

### ISSUE THREAD

**Issue by qwerty00ui88** [qwerty00ui88/solo-project-1#3]
## Tasks

- [ ] 회원가입 API 연결
- [ ] 로그인 API 연결
- [ ] 로그아웃 API 연결

**Comment by qwerty00ui88** [comment]
**에러 사항 설명**
로그인 시 쿠키 저장 안됨

**재현 단계**
1. 서버에서 쿠키 전송 성공
2. 쿠키 저장 안됨

**예상 결과**
쿠키 저장되어야 함

**실제 결과**
쿠키 저장 안됨

**해결 방법**
axios로 요청 시, withCredentials(CORS 요청에 자격 증명 정보(ex. 쿠키)를 포함 여부) 기본값은 false
-> `withCredentials: true`로 설정해주어야 함. 

```
// before
axios.get('https://example.com/api/data')
  .then(response => {
    console.log(response.data);
  })
  .catch(error => {
    console.error('Error:', error);
  });
```

```
// after
axios.get('https://example.com/api/data', {
  withCredentials: true
})
  .then(response => {
    console.log(response.data);
  })
  .catch(error => {
    console.error('Error:', error);
  });
```

**관련 정보**
- 참고 블로그: <a href = "https://velog.io/@gmtmoney2357/%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B6%80%ED%8A%B8-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%BF%A0%ED%82%A4-%EC%84%B8%EC%85%98#-%EC%84%B8%EC%85%98-%EC%84%A4%EC%A0%95" target="_blank">https://velog.io/@gmtmoney2357</a>
